### ISSUE TITLE
Does the script still work?

### ISSUE THREAD

**Issue by maisun** [simonpacis/DBA-Reposter#10]
Thanks for sharing the script! I'm not sure if the script still works (maybe DBA changed something in their API). When I run the script I received the error:
Traceback (most recent call last):
  File "dbareposter.py", line 203, in <module>
    if(r['success'] == True):
KeyError: 'success'

And the error message from DBA:
{'httpstatuscode': 403, 'description': 'Unauthorized DbaApiKey', 'errorcode': 'BadApiKey', 'userMessage': {'title': 'Opdater app', 'text': 'Du har en gammel version af DBA. Denne app understøttes ikke længere, hent venligst den nyeste version i App Store', 'actionText': 'Hent', 'actionLink': 'http://itunes.apple.com/dk/app/bilbasen/id448605988?l=da&mt=8&ls=1'}}
Some help is appreciated!

**Comment by mcj116** [comment]
If you update dbaapikey and User-Agent, it will work. Eg. try with this:
**User-Agent: dba/6.5.0 iPhone 13.5.1 (iPhone10,6)
dbaapikey: 16ca0020-560b-4ee4-f603-08d81dcb3572**
I grabbed it with Fiddler.

**Comment by mcj116** [comment]
> Thanks for sharing the script! I'm not sure if the script still works (maybe DBA changed something in their API). When I run the script I received the error:
> Traceback (most recent call last):
> File "dbareposter.py", line 203, in
> if(r['success'] == True):
> KeyError: 'success'
> 
> And the error message from DBA:
> {'httpstatuscode': 403, 'description': 'Unauthorized DbaApiKey', 'errorcode': 'BadApiKey', 'userMessage': {'title': 'Opdater app', 'text': 'Du har en gammel version af DBA. Denne app understøttes ikke længere, hent venligst den nyeste version i App Store', 'actionText': 'Hent', 'actionLink': '[http://itunes.apple.com/dk/app/bilbasen/id448605988?l=da&mt=8&ls=1'}}](http://itunes.apple.com/dk/app/bilbasen/id448605988?l=da&mt=8&ls=1'%7D%7D)
> Some help is appreciated!

**Comment by maisun** [comment]
> If you update dbaapikey and User-Agent, it will work. Eg. try with this:
> **User-Agent: dba/6.5.0 iPhone 13.5.1 (iPhone10,6) dbaapikey: 16ca0020-560b-4ee4-f603-08d81dcb3572**
> I grabbed it with Fiddler.

Thank you! Will give a try :)

**Comment by maisun** [comment]
Looks like the API key stops working now. How can I find out which API key to use? Thanks in advance!
